"""empty message

Revision ID: 573612b2b113
Revises: bb88a76fe1dd
Create Date: 2025-10-05 19:23:00.090490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573612b2b113'
down_revision = 'bb88a76fe1dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
